name: Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convert markdown to html
        run: |
          mkdir build
          pandoc index.md -o build/index.html

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy
        uses: actions/deploy-pages@v4